language: csharp
solution: Calculator.sln
install:
  - nuget restore Calculator.sln
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Calculator.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./lab01_tpTests/bin/Release/lab01_tpTests.dll
  
notifications:
  email:
    on_success: change
    on_failure: always
